tangent-opensource/hdBlackbird

- plugin/hdCycles/material.cpp
- plugin/ndrCycles/discovery.cpp
- plugin/ndrCycles/parser.cpp
- tools/houdini/hda_generator.cpp
Main PR for issue described here...
https://github.com/tangent-opensource/hdcycles/issues/28
> #28 - Made changes to support legal info:id. 

- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/basisCurves.h
- plugin/hdCycles/utils.cpp
- plugin/hdCycles/utils.h
- tools/houdini/hda_generator.cpp
Main PR for: https://github.com/tangent-opensource/hdcycles/issues/30
> #30 Added support for basisCurve primvars

- plugin/hdCycles/config.cpp
- plugin/hdCycles/config.h
- plugin/hdCycles/renderParam.cpp
> Added basic support to log progress of render

- plugin/hdCycles/config.cpp
- plugin/hdCycles/config.h
- plugin/hdCycles/material.cpp
- plugin/hdCycles/utils.cpp
- plugin/hdCycles/utils.h
This will allow all materials to dump their shadergraph to file for any given render.
> Dump material shader graph to file

- plugin/hdCycles/light.cpp
- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/renderParam.h
The default dome light would not disappear after adding lights. This now brings the behaviour in line with other Hydra delegates.
See https://github.com/tangent-opensource/hdcycles/issues/66 for more info
> Bugfix: Fixed default dome light behaviour

- plugin/hdCycles/basisCurves.cpp
Handles curve widths of different interpolations
> Bugfix: Fixed empty widths and width interpolations

- plugin/hdCycles/camera.cpp
Fixed the namespace of the camera enumerator
> Fixed merge typo

- package.py
* update cycles version
* auto os variants selection system
* remove old not needed variants
> package py update

- plugin/hdCycles/config.cpp
- plugin/hdCycles/light.cpp
- plugin/hdCycles/material.cpp
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/mesh.h
- plugin/hdCycles/meshRefiner.cpp
- plugin/hdCycles/meshRefiner.h
- plugin/hdCycles/renderBuffer.cpp
- plugin/hdCycles/renderPass.cpp
- plugin/ndrCycles/discovery.cpp
- plugin/ndrCycles/parser.cpp
> Warnings fix

- plugin/hdCycles/renderParam.cpp
Reverts tangent-opensource/hdcycles#123
> Revert "Sampling-related fixes"

- plugin/hdCycles/basisCurves.cpp
@skwerner After some investigation I have observed, that we had two problems with texture coordinates for hair:
* [Here](https://github.com/tangent-opensource/cycles/blob/master/src/render/attribute.cpp#L514) we can see that "size" of the `ATTR_STD_UV` attribute will be equivalent size to `ATTR_ELEMENT_CURVE`.
* [Here](https://github.com/tangent-opensource/cycles/blob/master/src/render/attribute.cpp#L210) size of the `ATTR_ELEMENT_CURVE` will result as `num_curves`.
* Shader request for STD_UV attribute made by Texture Coordinate Node will omit uv attributes that size does not match the size of `ATTR_STD_UV`. I debugged it  [here](https://github.com/tangent-opensource/cycles/blob/master/src/render/geometry.cpp#L669)
For the texture coordinates per vertex I create two attributes: …
> Hair texture coordinates

- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/points.cpp
- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/renderParam.h
- plugin/hdCycles/volume.cpp
No need to rely on sub-classes.  Less is more.
> Replace add/remove curve mesh with add/remove geometry

- plugin/hdCycles/light.cpp
- plugin/hdCycles/light.h
Cycles lights are normalized, so this patch will tweak the lights so that they can be un-normalized to conform with UsdLux lights. The following lights have been checked:
- Spotlight
- Sphere/Point
- Distant/Directional
- Disk
- Area
- Dome/Background
It also has been cross-referenced with the following renderers:
- Karma (Houdini 18.5)
- Renderman 23.5
- Arnold 6.2
This will cause a change in the looks for current light setups, be warned! Lights will need to be ticked with normalize on to have the previous look (some lights have been tweaked though exposure-wise to match the other renderers).
I believe I can see the disk-like characteristics of point/spot/sphere lights, compared to the other renderers the shape in the reflection doesn't align perfectly, and there is a little bit of …
> Cycles lights calibration + proper normalize toggle

- plugin/hdCycles/mesh.cpp
> fixing dead lock on point instances

- plugin/hdCycles/light.cpp
- The transform wouldn't update due to the shader node being optimised/folded away into the environment texture node, so we couldn't find & update it. The solution is to just rebuild the shader graph each transform update to the dome light if it has a texture assigned
- Suppress any translation from the mapping, this matches all the other Hydra delegates I've tested
- clang-format
> Domelight transform fixes

- package.py
The houdini_cycles pack will need usdCycles removed as a dependency next...
> Relocating env var from usdCycles to hdCycles, as the schema now lives here

- plugin/hdCycles/basisCurves.cpp
> Revisit schema and primvars for curves

- plugin/hdCycles/mesh.cpp
Handling non manifold meshes that fail to be refined because broken topology or whatever reason
> handle invalid meshes

- plugin/hdCycles/basisCurves.cpp
Last two PRs merged #210 and #208 addressed the same warning in non compatible ways.
> Fix merge bug

- plugin/hdCycles/volume.cpp
- plugin/hdCycles/volume.h
This PR fixes volume instancing. 
Test file: [volume_instance_test.zip](https://github.com/tangent-opensource/hdBlackbird/files/6618576/volume_instance_test.zip)
> Fix Volume Instancing

- plugin/hdCycles/transformSource.cpp
* Number of steps does not need to be odd any more
* No motion blur sent to coreBlackbird when all steps are the same
> Improvements to transformation motion blur:

- plugin/hdCycles/volume.cpp
- plugin/hdCycles/volume.h
This PR updates the volume object visibility flags similar to the mesh object.
> Update volume object visibility flags

- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/light.cpp
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/renderDelegate.h
- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/volume.cpp
- plugin/usdCycles/schema.usda
Dependent upon this merging in first:
https://github.com/tangent-opensource/coreBlackbird/pull/56
> Light-group support

- plugin/hdCycles/renderParam.cpp
**Changes**
In the viewport, blit each aov in parallel. This alleviates in part some of cpu usage problems in simple scenes and scales better.
> Blitting viewport aovs in parallel

- plugin/hdCycles/renderParam.cpp
Environment variables were not being set. Some others are missing but placing the texture ones in for now.
> Environment variables not being set for texture params

- plugin/hdCycles/basisCurves.cpp
Visibility flags for the hair were not updated.
> Remove visibility flags value and rely on HdBbRPrim UpdateObject method

- plugin/hdCycles/mesh.cpp
> Velocities and accelerations respect mesh motion blur settings

- CMakeLists.txt
- cmake/FindHoudiniUsd.cmake
- cmake/FindPixarUsd.cmake
- plugin/CMakeLists.txt
- plugin/usdImagingCycles/CMakeLists.txt
- plugin/usdImagingCycles/engine.cpp
- plugin/usdImagingCycles/engine.h
Adds render engine that produces images without GL context.
> Blackbird Engine
