- cmake/modules/FindCycles.cmake
The order in which cycles libraries are now synced with the order cycles links them for the standalone application.
This avoids undefined symbols errors when a library is linked before parts of it are requested by later libraries.
This PR fixes #3
> Fixing the undefined symbol problem under Linux (gcc)

- CMakeLists.txt
- cmake/defaults/msvcdefaults.cmake
The first block is copied verbatim from Pixar's msvcdefaults.cmake
> Fix some build errors I hit in VS2019

- plugin/hdCycles/mesh.cpp
Face varying triangulation is run even for vertex varying uvs.
Images from a sample scene where the plane uses vertex varying uvs.  These are Maya default primitive shapes.
Before:
After:
> Uvs with interpolation = "vertex" don't render correctly

- CMakeLists.txt
- plugin/hdCycles/CMakeLists.txt
- plugin/hdCycles/material.cpp
- plugin/hdCycles/openvdb_asset.cpp
- plugin/hdCycles/openvdb_asset.h
- plugin/hdCycles/renderDelegate.cpp
- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/volume.cpp
- plugin/hdCycles/volume.h
- plugin/ndrCycles/CMakeLists.txt
- plugin/ndrCycles/discovery.cpp
This allows Cycles to render OpenVDB USDVol volumes. Support for HdCycles volume materials is also included.
There is a known loading slowdown. This has yet been determined. It seems to be bottlenecked by Cycles internal texture loading functions. Blender Cycles internal does not experience this slowdown
> Feature: OpenVDB Volumes

- plugin/hdCycles/basisCurves.cpp
Cycles ingests radii for curves. Previously, our usd exporter from Blender would export the radius directly. However UsdGeomBasisCurves generally are stored as diameters. 
This change will also be made shortly in our opensource usd exporter.
(This commit also formats the file hence some additional changes)
> Bugfix: Treat widths as diameter 

- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/basisCurves.h
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/mesh.h
- plugin/hdCycles/utils.cpp
- plugin/hdCycles/utils.h
A recent commit introduced a mesh specific coordinate space util, this was a duplicate of a common util already implemented. The logic has been consolidated and should allow basisCurves to also properly have generated coords
> Bugfix: Consolidate mesh texture space utils

- plugin/hdCycles/material.cpp
- plugin/hdCycles/renderParam.cpp
In material sync, set_graph() was not being called (I think due to a previous cycles crash). 
Some code formatting also found its way into this PR.
This fixes volume material binding.
> Fix for volume materials

- plugin/hdCycles/material.cpp
For a brief period our houdini_cycles stored enums as tokens instead of strings. This allows support for these usd files.
There is no harm in adding this now, they function similarly enough for now, and this addition will only effect enums anyway,
> Added compatibility for enums stored as tokens

- plugin/hdCycles/config.cpp
- plugin/hdCycles/config.h
- plugin/hdCycles/light.cpp
- plugin/hdCycles/light.h
- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/renderParam.h
- Parameter changes on-sync will re-create a new shader graph and be applied via set_graph() calls
- As a result, removed excess shader member pointers they are not needed & prevents crashes
- Added support for textures on rect/quad lights (TODO: need to check if texture co-ords are consistent with other delegates)
- Fixed HDRI co-ordinates on dome/background lights (matches Houdini GL)
> Refining how lights work in hdCycles

- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/mesh.h
- plugin/hdCycles/utils.cpp
- plugin/hdCycles/utils.h
- plugin/ndrCycles/discovery.cpp
This PR is a step towards a more generic way of populating Cycles attributes from meshes.
This does not touch curves or other attributes. It eventually should be agnostic to all.
> Improvement: Arbitrary mesh attributes

- plugin/hdCycles/material.cpp
- plugin/hdCycles/utils.h
If USD is compiled without name spaces. `hdCycles` will not compile since `pxr` namespace does not exist. We don't have to use `pxr::` namespace because we are in between `PXR_NAMESPACE_OPEN_SCOPE` `PXR_NAMESPACE_CLOSE_SCOPE`
> remove pxr namespace

- plugin/hdCycles/light.cpp
As per https://github.com/tangent-opensource/hdcycles/issues/62
We now use the UsdLux schema to determine if shadows should be cast from a light.
Tested in an interactive Solaris session
> Switched from custom usdCycles schema to usdlux shadow schema

- plugin/hdCycles/material.cpp
Boolean sockets were never supported by HdCycles until now.
> Bugfix: Added support for Boolean sockets

- plugin/ndrCycles/discovery.cpp
Displacement shaders would fail as their ID was not found in the shader definition registry. This PR simply adds the definition.
Ideally, things should be done automatically through the Cycles API (either once or every time), like it's being done in the [hda shader generator](https://github.com/tangent-opensource/houdini_cycles/blob/main/scripts/cycles_shaders_generator/hda_generator.cpp). To not delay the next build, this will do in the meantime but the same issue could come up for future shaders.
> Added displacement node to shader definition registry

- plugin/hdCycles/camera.cpp
- plugin/hdCycles/camera.h
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/mesh.h
**Overview**
Enabling motion blur to be computed from velocities and accelerations.
**Changes**
- Triggering rebuild of the BVH for meshes with varying topology to prevent segfaults.
- Adding velocity, acceleration and angular velocity attributes to the Cycles mesh
**Comments**
Added frames per second to camera [as in the volume motion blur PR](https://github.com/tangent-opensource/hdcycles/pull/75), there should not be any conflicts.
See [Cycles PR](https://github.com/tangent-opensource/cycles/pull/7)
Without motion blur
With motion blur
> Enabling motion blur for geometries with varying topology

- plugin/hdCycles/mesh.cpp
The line in question was being printed even if the geometry had no normals. I tried to limit the print by checking if the original dirty bits included the normals (without the extra propagation), but no help.
Are all the initial bits set to dirty even if the primitive doesn't have that attribute?
> PopulateNormals warnings

- plugin/hdCycles/CMakeLists.txt
- plugin/hdCycles/debug_codes.h
- plugin/hdCycles/mesh.cpp
Issuing a possibly useful warning through its own debug code rather than a generic warning/error. This can be controlled through the environment variable `TF_DEBUG=HDCYCLES_MESH` or `TF_DEBUG=HDCYCLES_*` in the future.
In the future non fatal application-level messages should go through our custom codes and ideally the USD/Hydra warnings should disappear through better use of the API.
> First step with TF_DEBUG codes

- plugin/hdCycles/mesh.cpp
`_PopulateMotion` was left commented in one of the previous merges, this PR uncomments it and fixes a bug where the motion points attribute was not being added.
> Uncomment the code to compute the deform blur steps

- plugin/hdCycles/basisCurves.cpp
Adding the curve object to the scene only when geometry is available, this prevents crashes as described in #101.
I also added a lock to the scene to be consistent with other geometries.
Internal ticket #5628
> Deferring adding curve to scene to when geometry is available

- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/renderPass.cpp
Locking the display when reading from its pixel buffer. This caused crashes when the Houdini viewport was being resized as the display buffer was being deallocated during reading #102 
This [Cycles PR ](https://github.com/tangent-opensource/cycles/pull/20)is required.
> Lock cycles session display buffer

- plugin/hdCycles/openvdb_asset.h
- plugin/hdCycles/volume.cpp
- plugin/hdCycles/volume.h
Added a function to update the openvdb grid of the "HdCyclesVolumeLoader", which is cleared by the cycles "device_load_image" function. This grid is needed for constructing a mesh and was causing a crash when volumes are updated. 
Fixes PT-835
Testing procedure:
* Download the test file
* Render in viewport with cycles
* Disable transform and render a second time, HdCycles shouldn't crash anymore.
[test file](https://github.com/tangent-opensource/hdcycles/files/6207197/volume_update.zip)
> Fix hdCycles crash on updating volumes PT-835

- plugin/hdCycles/renderParam.cpp
- Blender backend sets AA samples back onto the session's global samples when in branched-path mode, overriding what's there
- Make sure to set the sampling pattern to PMJ when in adaptive sampling mode
- Make sure to only create one sample count pass when in adaptive sampling mode
> Sampling-related fixes

- plugin/hdCycles/renderParam.cpp
When there is no AOV specified, Houdini uses the token "C.*" as default which Cycles doesn't understand fully as it doesn't do LPEs yet, so this is a workaround to use HdAovTokens->color instead which is just the string "color".
> Default color AOV fix

- plugin/hdCycles/renderParam.cpp
This is dependent upon https://github.com/tangent-opensource/usdcycles/pull/3
Hdcycles will use the default samples option if aa_samples is set to 0 like the previous behaviour. If aa_samples is set higher than 0, it'll be used instead in branched-path mode, which is the expected behaviour.
The progress of 400% reported is another issue which might need to be looked at closer to see what's happening there.
> Don't apply AA samples when it is 0.

- plugin/hdCycles/renderParam.cpp
This lock was causing a deadlock on Linux and preventing tiled rendering from working, found this while debugging the aa_samples issue.
> Remove lock from tile rendering callback

- plugin/hdCycles/config.cpp
- plugin/hdCycles/config.h
- plugin/hdCycles/renderParam.cpp
Adding functionality to respect `-j`/`--threads` from Husk. This is a temporary solution. When SideFx exposes Husk's TfTokens they can be taken from a header distributed with Houdini.
> Use tbb to set number of threads

- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/light.cpp
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/volume.cpp
Always set default values at the start of a sync, so that when a "do nothing" is set in Solaris, or a different node is picked, it'll start back with sane defaults. This addresses curves, lights, meshes and volumes.
TODO: All global values in renderParam need the defaults set on any scene refresh also, but for now we can just be explicit with our RenderSettings node (seems like no other delegate works correctly here as well, including PRMan).
And as an extra note, we may need to be vigilant on any new schema that gets added here. We can also use the cycles node API to set built-in defaults if we prefer also, but lets do that once we upgrade to the latest cycles API just in case they have a new/different way now.
> Always set default values at the start of a sync

- plugin/hdCycles/material.cpp
Certain scenes contain materials that the index is out of range. I am not sure if the check `index < socket.size()` is the right way to go to prevent scenes from crashing.
> Distribution enum value out of range and fallback to default GGX

- plugin/hdCycles/CMakeLists.txt
- plugin/hdCycles/objectSource.cpp
- plugin/hdCycles/objectSource.h
- plugin/hdCycles/renderDelegate.cpp
- plugin/hdCycles/renderDelegate.h
- plugin/hdCycles/renderPass.cpp
- plugin/hdCycles/renderPassState.cpp
- plugin/hdCycles/renderPassState.h
- plugin/hdCycles/resourceRegistry.cpp
In some situations switching between Houdini viewport and the camera causes Houdini to crash. In the process of switching `HdRenderPassState` can hold null camera pointer. That happens because after removing `SPrim` new `HdCamera` has not been created yet.
> fixing null ptr camera

- plugin/hdCycles/renderDelegate.cpp
- plugin/hdCycles/renderDelegate.h
New diagnostic delegate allows us to output errors and fatal errors to `stdout`. Easily if we wish we could modify the implementation and save the diagnostic information to a file.
> Add new Diagnostic Delegate to re-direct errors to stdout

- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/utils.cpp
- plugin/hdCycles/utils.h
- plugin/usdCycles/schema.usda
Tile size was read as GfVec2i while the schema defines it as GfVec2f. Issuing a warning for now. 
Maybe this should be automatically converted, but strict compliance with the schema is also good.
Internal ticket #6655
> Changed the tile_size render setting schema type to integer 

- .clang-format
- plugin/hdCycles/attributeSource.cpp
- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/basisCurves.h
- plugin/hdCycles/camera.cpp
- plugin/hdCycles/config.cpp
- plugin/hdCycles/config.h
- plugin/hdCycles/hdcycles.h
- plugin/hdCycles/instancer.cpp
- plugin/hdCycles/light.cpp
- plugin/hdCycles/light.h
- plugin/hdCycles/material.cpp
- plugin/hdCycles/material.h
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/meshRefiner.cpp
- plugin/hdCycles/meshRefiner.h
- plugin/hdCycles/objectSource.cpp
- plugin/hdCycles/points.cpp
- plugin/hdCycles/renderBuffer.cpp
- plugin/hdCycles/renderDelegate.cpp
- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/renderPass.cpp
- plugin/hdCycles/renderPass.h
- plugin/hdCycles/renderPassState.cpp
- plugin/hdCycles/resourceRegistry.h
- plugin/hdCycles/utils.cpp
- plugin/hdCycles/volume.cpp
- plugin/usdCycles/moduleDeps.cpp
Turn off super annoying clang format option:
```
AlignConsecutiveAssignments: true 
```
This feature makes our PRs very difficult to read. For example #163 where there is a one line, that is the most important part of that PR. But it's gone because it's being hidden under formatting. 
Also, it gets better! When we have already setup alignment such as:
```
m_cyclesLight->use_diffuse      = true;
m_cyclesLight->use_glossy       = true;
m_cyclesLight->use_transmission = true;
m_cyclesLight->use_scatter      = true;
m_cyclesLight->use_mis          = true;
m_cyclesLight->is_portal        = false;
m_cyclesLight->samples          = 1;
m_cyclesLight->max_bounces      = 1024;
```
removing `m_cyclesLight->use_transmission = true;` from that list will cause entire code block to be reformatted. 
Burn …
> Remove annoying clang format options

- plugin/hdCycles/renderParam.cpp
- Also bugfixes the environment variable overriding it after the schema defines it
> Enables the ability to toggle between path/branched_path integrators for the viewport

- plugin/hdCycles/material.cpp
- plugin/hdCycles/material.h
This patch checks the output nodes of the shader graph for preview materials. If preview and Cycles materials are present then the preview ones are disconnected, otherwise the shader graph is left untouched.
Do you foresee any problems with this patch? I tested different combinations and seems to produce what I would expect to see. 
Resolves internal ticket 6513
> Disconnecting preview shader outputs when they override Cycles'

- plugin/hdCycles/light.cpp
- plugin/hdCycles/renderParam.h
- plugin/usdCycles/schema.usda
- Fixed lights not being square-sampled when enabled in the render settings
This PR will require houdini_cycles to be updated to show the map_resolution schema
> Added map_resolution schema for dome lights importance sampling

- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/renderParam.cpp
- plugin/usdCycles/schema.usda
- Needed as the layer name can differ from the source name
- Added ambient occlusion, it was missing
> Cryptomatte metadata now hashes the exr layer name instead of source name

- plugin/hdCycles/mesh.cpp
Override refine level from the value that comes from the schema. That turns off control through complexity but allows us explicit control over the subdivision.
> override refineLevel by schema

- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/basisCurves.h
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/mesh.h
- plugin/hdCycles/points.cpp
- plugin/hdCycles/points.h
- plugin/usdCycles/schema.usda
* new schema for deformation and transformation motion blur
* by default motion blur is on
* transformation samples set to 3
* deformation samples set to 3
* individual control over motion blur, deformation, transformation samples per object
> Motion blur schema update and multisegment deformation motion blur

- plugin/hdCycles/renderDelegate.h
- plugin/hdCycles/renderParam.cpp
- plugin/usdCycles/schema.usda
- Simplified schema & removed legacy options from SessionParams (now in DenoiseParams), removed NLM as this will be deprecated in future Cycles releases (let me know @skwerner  if this is ok to do)
- Can render DenoiseNormal and DenoiseAlbedo
- No actual denoising is done in the renderer (yet)
> Implementing first part of denoise

- plugin/hdCycles/renderBuffer.cpp
- plugin/hdCycles/renderBuffer.h
- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/renderParam.h
Uses the dataWindowNDC attribute as cropping region for coreBlackbird.
It requires this [coreBlackbird PR](https://github.com/tangent-opensource/coreBlackbird/pull/58)
> Handling crop render settings (dataWindowNDC)

- plugin/hdCycles/material.cpp
When encountering shader nodes that could not be converted to a
Blackbird equivalent, the code was still trying to operate on them.
> Fixed possible NULL pointer dereference

- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/mesh.h
- plugin/hdCycles/renderParam.cpp
- plugin/hdCycles/renderParam.h
Instead of adding/deleting instances one by one, they're now allocated,
added, freed and removed in blocks. This makes it possible to use
millions of instances in an interactive session.
> Improved instancing performance

- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/mesh.h
This patch populates custom motion normals for meshes. It requires this [Cycles PR](https://github.com/tangent-opensource/coreBlackbird/pull/60)
Testing it on assets with motion blur/subdivision and seems to behave as expected. Will do some further tests before merging, but it's ready to be reviewed.
@bareya Does the current solution suffice for now? Might not be super elegant but at least avoids duplicating too much code. We will eventually have to revisit the timesampled primvars
> Mesh motion normals

- plugin/hdCycles/renderParam.cpp
The display code path was missing support for custom passes, which use a different name.
> Custom aovs in display mode

- plugin/hdCycles/material.cpp
This PR Checks for Volume connection to an Add Closure node and connects the output to "Volume" input if there is one. This is required for being able to connect volumetric nodes (scatter, absorption, etc.) to Add Closure and Mix Closure nodes. 
This PR depends on houdiniBlackbird PR 9 to be merged.
> Add Closure Volume Suport

- plugin/hdCycles/CMakeLists.txt
- plugin/hdCycles/basisCurves.cpp
- plugin/hdCycles/basisCurves.h
- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/mesh.h
- plugin/hdCycles/points.cpp
- plugin/hdCycles/points.h
- plugin/hdCycles/rprim.h
- plugin/hdCycles/volume.cpp
- plugin/hdCycles/volume.h
Remove code duplication and slide new `HdBbRPrim` class under mesh, points and curves. `HdBbRPrim` carries helper methods to manage object properties.
> Wrap common settings under HdBbRPrim

- plugin/hdCycles/mesh.cpp
Fixes:
* excessive memory allocation(caused by uninitialized refine level)
* prototypes are removed from the scene every time instancer is marked dirty.
> Assign visibility flags from prototype to instances

- plugin/hdCycles/mesh.cpp
Features:
* copy `displayColour` primvar from instancer to `ccl::Object` instances
* `asset_name` becomes `<instancer_path>/instance_index`
* `lightgroup` copied from the prototype
* `visibility` copied from the prototype
> Apply displayColor to the ccl::Object instances

- plugin/hdCycles/renderParam.cpp
- Removed unused `use_adaptive_sampling` option in the film
- Forcing the integrator to use PMJ if adaptive sampling is enabled
- Setting auxiliary render passes when the cycles session has already been created
Related to FD #8584
> Render settings for adaptive sampling

- plugin/hdCycles/renderParam.cpp
@dedoardo pointed this one out awhile back. Probably good as on the farm we set by USD schema and it isn't working quite right.
> Using eval to set texture configs

- plugin/hdCycles/mesh.cpp
Enabling motion blur on the cycles mesh if the hdcycles object has them enabled. Sorry, in [the previous PR](https://github.com/tangent-opensource/hdBlackbird/pull/239) I assumed that they were set outside of the individual functions.
Now the behavior is consistent with PopulateMotion.
> Transferring motion blur settings to Cycles mesh 

- plugin/hdCycles/mesh.cpp
- plugin/hdCycles/mesh.h
- plugin/usdCycles/schema.usda
By default compute tangents using Mikktspace to match export workflow, but allow usage of limit surface tangents through a new setting. 
FD-9026
> Default to computing tangents using mikktspace

- plugin/hdCycles/material.cpp
Blender->USD appears to write the "Filmic sRGB" space as "Filmic_sRGB".
Added special cases to change those color spaces back to our names.
> Better reading of Blender color spaces

- plugin/hdCycles/light.cpp
Some light fixes, make sure size is 0.0f when a point light is specified (no radius schema, so it needs to be set to 0.0f). Cylinder light intensity set to 0.0f to indicate that they are not supported (yet). Addresses FD #8973
> Point light fix + cylinder light disable

- plugin/hdCycles/volume.cpp
- plugin/hdCycles/volume.h
**Description**
The volume synchronization code does not read primvars besides common object setting. This code reads constant primvars into the geometry attributes.
For the primvars to be used in attribute nodes and then plugged to volume shaders, you need [this core patch](https://github.com/tangent-opensource/coreBlackbird/pull/96).
FD-8574
**Changes**
- Added object attribute source for constant primvars in the volume primitive
**Test**
Here is a test file with "customColor" and "customDensity" connected to a principled volume node
[test-volume-constant-primvars.zip](https://github.com/tangent-opensource/hdBlackbird/files/6864364/test-volume-constant-primvars.zip)
> Sourcing constant primvars in volumes

- cmake/FindHoudiniUsd.cmake
Houdini `usdGenSchema` script requires a license to generate scheme in the docker image. The script is almost identical as the one distributed by Pixar. This little PR helps us to generate schema in Houdini docker without a license.
> Allow custom schema generator for Houdini docker
